%read in data file containing various iron levels and absorption

[hb,sf,stfr,znpp,absorp]...
    =textread('/Users/Ali/Documents/Nutrition and Global Health/Fe_absp.csv','%f %f %f %f %f'...
    ,'delimiter',',','emptyvalue',NaN,'headerlines',1);